Repository JNU-SW-Capstone-Team11-CAPSROCK/Team11_CAPSROCK_BE, pull requests merged in 2025-04, with the labels that each got.

#9 [Week5] API 응답문제 해결을 위한 PR
  src/main/java/capsrock/mainPage/client/WeatherInfoClient.java
  src/main/java/capsrock/mainPage/dto/response/WeatherApiResponse.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/main/resources/application-weather.properties
Labels: 🐛 bug

#13 [Week5] 다음 23시간 날씨를 가져오지 못하는 버그 수정
  src/main/java/capsrock/mainPage/dto/Dashboard.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/main/java/capsrock/mainPage/util/TimeUtil.java
  src/test/java/capsrock/mainPage/service/MainPageServiceTest.java
Labels: 🐛 bug

#14 [Week5] 다음 23시간 날씨 -> 강수량, 강수확률 추가
  src/main/java/capsrock/mainPage/dto/Next23HoursWeather.java
  src/main/java/capsrock/mainPage/dto/TodayWeather.java
  src/main/java/capsrock/mainPage/dto/response/MainPageResponse.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/test/java/capsrock/mainPage/service/MainPageServiceTest.java
Labels: ✨feat

#15 [Week5] DTO 및 메서드 이름 변경
  src/main/java/capsrock/mainPage/dto/Next7DaysWeather.java
  src/main/java/capsrock/mainPage/dto/response/MainPageResponse.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
Labels: :recycle: refactor

#16 [Week5] 기상청 api -> weatherAPi
  src/main/java/capsrock/mainPage/client/WeatherInfoClient.java
  src/main/java/capsrock/mainPage/config/WeatherRequestConfig.java
  src/main/java/capsrock/mainPage/controller/MainPageController.java
  src/main/java/capsrock/mainPage/dto/Next23HoursWeather.java
  src/main/java/capsrock/mainPage/dto/response/HourlyWeatherResponse.java
  src/main/java/capsrock/mainPage/dto/response/WeatherApiResponse.java
  src/main/java/capsrock/mainPage/enums/WeatherEnum.java
  src/main/java/capsrock/mainPage/service/HourlyWeatherService.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/main/java/capsrock/mainPage/util/TimeUtil.java
  src/main/resources/application-weather.properties
  src/test/java/capsrock/mainPage/client/WeatherInfoClientTest.java
  src/test/java/capsrock/mainPage/service/MainPageServiceTest.java
Labels: :recycle: refactor, 🚧 incomplete

#17 [Week5] 메인페이지 기능 구현
  src/main/java/capsrock/geocoding/client/GeocodingClient.java
  src/main/java/capsrock/geocoding/config/GeocodingRequestConfig.java
  src/main/java/capsrock/geocoding/config/GeocodingRequestRegistrar.java
  src/main/java/capsrock/geocoding/dto/response/ReverseGeocodingResponse.java
  src/main/java/capsrock/geocoding/dto/service/AddressDTO.java
  src/main/java/capsrock/location/geocoding/config/GeocodingRequestConfig.java
  src/main/java/capsrock/location/grid/config/GridRequestRegistrar.java
  src/main/java/capsrock/location/grid/dto/Grid.java
  src/main/java/capsrock/location/grid/util/GpsToGridConverter.java
  src/main/java/capsrock/mainPage/client/WeatherInfoClient.java
  src/main/java/capsrock/mainPage/config/WeatherRequestRegistrar.java
  src/main/java/capsrock/mainPage/controller/MainPageController.java
  src/main/java/capsrock/mainPage/dto/Dashboard.java
  src/main/java/capsrock/mainPage/dto/Next7DaysWeather.java
  src/main/java/capsrock/mainPage/dto/TimeDTO.java
  src/main/java/capsrock/mainPage/dto/response/DailyWeatherResponse.java
  src/main/java/capsrock/mainPage/dto/response/MainPageResponse.java
  src/main/java/capsrock/mainPage/dto/service/Dashboard.java
  src/main/java/capsrock/mainPage/dto/service/Next23HoursWeather.java
  src/main/java/capsrock/mainPage/dto/service/Next7DaysWeather.java
  src/main/java/capsrock/mainPage/service/DailyWeatherService.java
  src/main/java/capsrock/mainPage/service/HourlyWeatherService.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/main/java/capsrock/mainPage/util/TimeUtil.java
  src/main/resources/application-grid.properties
  src/test/java/capsrock/geocoding/client/GeocodingClientTest.java
  src/test/java/capsrock/mainPage/client/WeatherInfoClientTest.java
  src/test/java/capsrock/mainPage/service/DailyWeatherServiceTest.java
  src/test/java/capsrock/mainPage/service/HourlyWeatherServiceTest.java
  src/test/java/capsrock/mainPage/service/MainPageServiceTest.java
Labels: ✨feat

#28 [Week6] GeoCodingService 를 거치도록 리팩터링
  src/main/java/capsrock/location/geocoding/service/GeocodingService.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
Labels: 🔨 enhancement, :recycle: refactor

#29 [Week9] 옷차림 예측 기능 뼈대 부분 추가
  build.gradle
  src/main/java/capsrock/Application.java
  src/main/java/capsrock/clothing/feedback/controller/ClothingFeedbackController.java
  src/main/java/capsrock/clothing/feedback/service/ClothingFeedbackService.java
  src/main/java/capsrock/clothing/prediction/client/ClothingGeminiClient.java
  src/main/java/capsrock/clothing/prediction/config/GeminiPredictionRequestConfig.java
  src/main/java/capsrock/clothing/prediction/config/GeminiPredictionRequestRegistrar.java
  src/main/java/capsrock/clothing/prediction/dto/request/ClothingData.java
  src/main/java/capsrock/clothing/prediction/dto/request/ClothingPredictionRequest.java
  src/main/java/capsrock/clothing/prediction/dto/request/MorningNoonEvening.java
  src/main/java/capsrock/clothing/prediction/dto/request/OneUserData.java
  src/main/java/capsrock/clothing/prediction/dto/response/ClothingPredictionResponse.java
  src/main/java/capsrock/clothing/prediction/dto/response/CorrectionValues.java
  src/main/java/capsrock/clothing/prediction/dto/response/UserPrediction.java
  src/main/java/capsrock/clothing/prediction/enums/GeminiModel.java
  src/main/java/capsrock/clothing/prediction/factory/ClothingPredictionResponseSchemaFactory.java
  src/main/java/capsrock/clothing/prediction/service/ClothingPredictService.java
  src/main/java/capsrock/common/config/WebMvcConfig.java
  src/main/java/capsrock/dto/request/ClothingFeedbackRequest.java
  src/main/java/capsrock/location/geocoding/client/GeocodingClient.java
  src/main/java/capsrock/location/geocoding/config/GeocodingRequestConfig.java
  src/main/java/capsrock/location/geocoding/config/GeocodingRequestRegistrar.java
  src/main/java/capsrock/location/geocoding/dto/response/ReverseGeocodingResponse.java
  src/main/java/capsrock/location/geocoding/dto/service/AddressDTO.java
  src/main/java/capsrock/location/geocoding/service/GeocodingService.java
  src/main/java/capsrock/mainPage/client/WeatherInfoClient.java
  src/main/java/capsrock/mainPage/dto/response/DailyWeatherResponse.java
  src/main/java/capsrock/mainPage/dto/response/MainPageResponse.java
  src/main/java/capsrock/mainPage/dto/service/Dashboard.java
  src/main/java/capsrock/mainPage/dto/service/NextFewDaysWeather.java
  src/main/java/capsrock/mainPage/service/DailyWeatherService.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/main/java/capsrock/member/controller/MemberController.java
  src/main/java/capsrock/member/dto/MemberInfoDTO.java
  src/main/java/capsrock/member/dto/MemberLoginDTO.java
  src/main/java/capsrock/member/model/entity/Member.java
  src/main/java/capsrock/member/model/vo/Email.java
  src/main/java/capsrock/member/repository/MemberRepository.java
  src/main/java/capsrock/member/service/MemberService.java
  src/main/resources/application-gemini.properties
  src/main/resources/clothingPredictionResponseSchema.json
  src/test/java/capsrock/clothing/prediction/client/ClothingGeminiClientTest.java
  src/test/java/capsrock/geocoding/client/GeocodingClientTest.java
  src/test/java/capsrock/mainPage/client/WeatherInfoClientTest.java
  src/test/java/capsrock/mainPage/service/DailyWeatherServiceTest.java
Labels: ✨feat

#31 [Week9] lombok, spring security 적용
  build.gradle
  src/main/java/capsrock/clothing/feedback/controller/ClothingFeedbackController.java
  src/main/java/capsrock/clothing/prediction/client/ClothingGeminiClient.java
  src/main/java/capsrock/clothing/prediction/dto/response/ClothingPredictionResponse.java
  src/main/java/capsrock/clothing/prediction/dto/response/CorrectionValues.java
  src/main/java/capsrock/clothing/prediction/dto/response/UserPrediction.java
  src/main/java/capsrock/clothing/prediction/factory/ClothingPredictionResponseSchemaFactory.java
  src/main/java/capsrock/clothing/prediction/service/ClothingPredictService.java
  src/main/java/capsrock/location/geocoding/service/GeocodingService.java
  src/main/java/capsrock/mainPage/client/WeatherInfoClient.java
  src/main/java/capsrock/mainPage/controller/MainPageController.java
  src/main/java/capsrock/mainPage/service/DailyWeatherService.java
  src/main/java/capsrock/mainPage/service/HourlyWeatherService.java
  src/main/java/capsrock/mainPage/service/MainPageService.java
  src/main/java/capsrock/member/controller/MemberController.java
  src/main/java/capsrock/member/model/entity/Member.java
  src/main/java/capsrock/member/model/vo/Email.java
  src/main/java/capsrock/member/repository/MemberRepository.java
  src/main/java/capsrock/member/service/MemberService.java
  src/main/resources/application.properties
Labels: ✨feat
